### ISSUE TITLE
AttributeError:'NoneType' object has no attribute 'shape'

### ISSUE THREAD

**Issue by EchoYGemini** [Whiffe/Custom-ava-dataset_Custom-Spatio-Temporally-Action-Video-Dataset#2]
您好，我在运行第九步这行代码的时候python yolov5_to_deepsort.py --source /home/Custom-ava-dataset_Custom-Spatio-Temporally-Action-Video-Dataset/Dataset/frames

报错:
Traceback (most recent call last):
  File "yolov5_to_deepsort.py", line 136, in <module>
    detect(opt)
  File "yolov5_to_deepsort.py", line 59, in detect
    imgsz = tempImg.shape
AttributeError: 'NoneType' object has no attribute 'shape'

前面都一切正常呢，不知道怎么回事

**Comment by EchoYGemini** [comment]
解决了，source后面接的那个地址没写对

**Comment by shnulailai** [comment]
> 解决了，source后面接的那个地址没写对

你好，请问你项目剩余全部的部分都跑通了吗？

**Comment by EchoYGemini** [comment]
你好，剩余的都跑通了的




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年6月27日(星期一) 中午1:52
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Whiffe/Custom-ava-dataset_Custom-Spatio-Temporally-Action-Video-Dataset] AttributeError:&#39;NoneType&#39; object has no attribute &#39;shape&#39; (Issue #2)





  
解决了，source后面接的那个地址没写对
  
你好，请问你项目剩余全部的部分都跑通了吗？

**Comment by shnulailai** [comment]
您的来信我已经收到了！

**Comment by shnulailai** [comment]
> 你好，剩余的都跑通了的
> 

> 你好，剩余的都跑通了的
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2022年6月27日(星期一) 中午1:52 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [Whiffe/Custom-ava-dataset_Custom-Spatio-Temporally-Action-Video-Dataset] AttributeError:&#39;NoneType&#39; object has no attribute &#39;shape&#39; (Issue #2) 解决了，source后面接的那个地址没写对 你好，请问你项目剩余全部的部分都跑通了吗？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

好的，谢谢你，我之前遇到的问题在issues也提到了，但是现在还没有解决，我再换个环境试试吧

**Comment by duckburgerhill** [comment]
> 您好，我在运行第九步这行代码的时候python yolov5_to_deepsort.py --source /home/Custom-ava-dataset_Custom-Spatio-Temporally-Action-Video-Dataset/Dataset/frames
> 
> 报错: Traceback (most recent call last): File "yolov5_to_deepsort.py", line 136, in detect(opt) File "yolov5_to_deepsort.py", line 59, in detect imgsz = tempImg.shape AttributeError: 'NoneType' object has no attribute 'shape'
> 
> 前面都一切正常呢，不知道怎么回事

你好，请问你有没有遇到在修正train_temp的时候，运行train.py，出现报错：
Traceback (most recent call last):
  File "train.py", line 76, in <module>
    update_train_temp(videoName, index, maxId)
  File "train.py", line 27, in update_train_temp
    if train_temp[index + index3 + 1][-1] == '-1':
IndexError: list index out of range
这个情况请问你知道是什么原因吗？

**Comment by shnulailai** [comment]
您的来信我已经收到了！

**Comment by EchoYGemini** [comment]
请问你是不是via标注的时候自己新增了框？去掉试一下




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Whiffe/Custom-ava-dataset_Custom-Spatio-Temporally-Action-Video-Dataset"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年7月28日(星期四) 中午12:07
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Whiffe/Custom-ava-dataset_Custom-Spatio-Temporally-Action-Video-Dataset] AttributeError:'NoneType' object has no attribute 'shape' (Issue #2)





  
您好，我在运行第九步这行代码的时候python yolov5_to_deepsort.py --source /home/Custom-ava-dataset_Custom-Spatio-Temporally-Action-Video-Dataset/Dataset/frames
 
报错: Traceback (most recent call last): File "yolov5_to_deepsort.py", line 136, in detect(opt) File "yolov5_to_deepsort.py", line 59, in detect imgsz = tempImg.shape AttributeError: 'NoneType' object has no attribute 'shape'
 
前面都一切正常呢，不知道怎么回事
  
你好，请问你有没有遇到在修正train_temp的时候，运行train.py，出现报错：
 Traceback (most recent call last):
 File "train.py", line 76, in 
 update_train_temp(videoName, index, maxId)
 File "train.py", line 27, in update_train_temp
 if train_temp[index + index3 + 1][-1] == '-1':
 IndexError: list index out of range
 这个情况请问你知道是什么原因吗？

**Comment by duckburgerhill** [comment]
没有唉，我之前以为是新增框的原因，后来就只删除不新增了。但是还是会报这个错。


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Whiffe/Custom-ava-dataset_Custom-Spatio-Temporally-Action-Video-Dataset"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年7月28日(星期四) 下午3:43
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Whiffe/Custom-ava-dataset_Custom-Spatio-Temporally-Action-Video-Dataset] AttributeError:'NoneType' object has no attribute 'shape' (Issue #2)





 请问你是不是via标注的时候自己新增了框？去掉试一下 
 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人:                                                                                                                        "Whiffe/Custom-ava-dataset_Custom-Spatio-Temporally-Action-Video-Dataset"                                                                                    ***@***.***&amp;gt;; 
 发送时间:&amp;nbsp;2022年7月28日(星期四) 中午12:07 
 ***@***.***&amp;gt;; 
 ***@***.******@***.***&amp;gt;; 
 主题:&amp;nbsp;Re: [Whiffe/Custom-ava-dataset_Custom-Spatio-Temporally-Action-Video-Dataset] AttributeError:'NoneType' object has no attribute 'shape' (Issue #2) 
 
 
 
 
 
    
 您好，我在运行第九步这行代码的时候python yolov5_to_deepsort.py --source /home/Custom-ava-dataset_Custom-Spatio-Temporally-Action-Video-Dataset/Dataset/frames 
   
 报错: Traceback (most recent call last): File "yolov5_to_deepsort.py", line 136, in detect(opt) File "yolov5_to_deepsort.py", line 59, in detect imgsz = tempImg.shape AttributeError: 'NoneType' object has no attribute 'shape' 
   
 前面都一切正常呢，不知道怎么回事 
    
 你好，请问你有没有遇到在修正train_temp的时候，运行train.py，出现报错： 
  Traceback (most recent call last): 
  File "train.py", line 76, in  
  update_train_temp(videoName, index, maxId) 
  File "train.py", line 27, in update_train_temp 
  if train_temp[index + index3 + 1][-1] == '-1': 
  IndexError: list index out of range 
  这个情况请问你知道是什么原因吗？

**Comment by shnulailai** [comment]
您的来信我已经收到了！

**Comment by xiyangyang99** [comment]
> > 您好，我在运行第九步这行代码的时候python yolov5_to_deepsort.py --source /home/Custom-ava-dataset_Custom-Spatio-Temporally-Action-Video-Dataset/Dataset/frames
> > 报错: Traceback (most recent call last): File "yolov5_to_deepsort.py", line 136, in detect(opt) File "yolov5_to_deepsort.py", line 59, in detect imgsz = tempImg.shape AttributeError: 'NoneType' object has no attribute 'shape'
> > 前面都一切正常呢，不知道怎么回事
> 
> 你好，请问你有没有遇到在修正train_temp的时候，运行train.py，出现报错： Traceback (most recent call last): File "train.py", line 76, in update_train_temp(videoName, index, maxId) File "train.py", line 27, in update_train_temp if train_temp[index + index3 + 1][-1] == '-1': IndexError: list index out of range 这个情况请问你知道是什么原因吗？

我也出现了这个问题
